#!/usr/bin/env python3
"""Bundle Lua modules and stage a self-contained Ly configuration (stdlib only)."""
import argparse
import json
from pathlib import Path
import re
import shutil
import shlex

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src"
ANIMATION = SOURCE / "animation"


def quote(value):
    # JSON's ordinary quoted strings are Lua-compatible for filesystem paths.
    value = str(value)
    if any(ord(c) < 32 for c in value):
        raise ValueError("Paths must not contain control characters")
    return json.dumps(value, ensure_ascii=False)


def bundle(root=ANIMATION):
    names = [s.strip() for s in (root / "modules.txt").read_text().splitlines()
             if s.strip() and not s.lstrip().startswith("#")]
    if len(names) != len(set(names)):
        raise ValueError("Duplicate module in modules.txt")
    sources = {}
    for name in names:
        if not re.fullmatch(r"[a-z_][a-z0-9_]*(\.[a-z_][a-z0-9_]*)*", name):
            raise ValueError(f"Invalid module name: {name}")
        path = root / (name.replace(".", "/") + ".lua")
        if not path.is_file():
            raise ValueError(f"Missing module: {name} ({path})")
        sources[name] = path.read_text()
    entry = (root / "anime.lua").read_text()
    for name, source in {**sources, "entry": entry}.items():
        for dep in re.findall(r'\brequire\s*\(\s*["\']([^"\']+)["\']\s*\)', source):
            if dep not in sources:
                raise ValueError(f"{name}: unlisted module {dep}")
    parts = ['-- GENERATED by tools/build.py; edit src/animation instead.\n',
             'local factories, cache, loading = {}, {}, {}\n',
             '''local function require(name)
    if cache[name] ~= nil then return cache[name] end
    local factory = factories[name]
    if not factory then error("PRTS: unknown embedded module " .. tostring(name)) end
    if loading[name] then error("PRTS: circular module " .. name) end
    loading[name] = true
    local result = factory(require)
    if result == nil then result = true end
    cache[name], loading[name] = result, nil
    return result
end
''']
    for name, source in sources.items():
        parts.append(f'\n-- module: {name}\nfactories[{quote(name)}] = function(require)\n{source}\nend\n')
    parts.append("\n-- entry point\ndo\n" + entry + "\nend\n")
    return "".join(parts)


def stage(output, runtime, preview=False):
    compiled = bundle()  # Fail before copying anything.
    output, runtime = Path(output).absolute(), Path(runtime).absolute()
    if output == SOURCE or SOURCE in output.parents or output == ROOT or output in ROOT.parents:
        raise ValueError("Build output must not overwrite source or a parent directory")
    output.mkdir(parents=True, exist_ok=True)
    if output.is_symlink() or any(p.is_symlink() for p in output.rglob("*")):
        raise ValueError("Refusing symlinked build output")
    for source in SOURCE.iterdir():
        if source.name == "animation":
            continue
        if source.is_dir():
            shutil.copytree(source, output / source.name, dirs_exist_ok=True)
        else:
            shutil.copy2(source, output / source.name)
    (output / "animation").mkdir(exist_ok=True)
    (output / "animation" / "anime.lua").write_text(compiled)
    config = (SOURCE / "config.lua").read_text()
    config += "\n-- Generated deployment paths.\n"
    for key, relative in {
        "lua_animation_file": "animation/anime.lua", "custom_sessions": "custom-sessions",
        "save_file_dir": "", "setup_cmd": "setup.sh", "start_cmd": "startup.sh",
    }.items():
        value = str(runtime / relative)
        if key.endswith("_cmd"):
            value = shlex.quote(value)
        config += f"ly.{key} = {quote(value)}\n"
    if preview:
        # This is a UI preview, never a second working system greeter.
        config += '''
ly.save_file_dir = nil
ly.start_cmd = nil
ly.setup_cmd = nil
ly.shutdown_key = nil
ly.restart_key = nil
ly.brightness_up_key = nil
ly.brightness_down_key = nil
ly.service_name = "prts-preview-no-auth"
ly.allow_empty_password = false
ly.auto_login_user = nil
ly.auto_login_session = nil
ly.type_username = true
ly.ly_log = nil
'''
    (output / "config.lua").write_text(config)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "build")
    parser.add_argument("--runtime-dir", type=Path, help="Final installation path, defaults to output")
    parser.add_argument("--preview", action="store_true")
    args = parser.parse_args()
    try:
        print(stage(args.output, args.runtime_dir or args.output, args.preview))
    except (ValueError, OSError) as error:
        parser.exit(1, f"PRTS build failed: {error}\n")


if __name__ == "__main__":
    main()
