#!/usr/bin/env bash
# 在 Ly 上启用/停用 KMSCON VT，以使用 TrueType 字体（JetBrainsMono 等）。
# 说明见 docs/kmscon.md。系统改动需要 root。
set -euo pipefail

DROPIN_DIR='/etc/systemd/system/ly-kmsconvt@.service.d'
DROPIN="$DROPIN_DIR/10-font.conf"
DEFAULT_TTY='tty1'
TRIAL_TTY='tty3'

usage() {
    cat <<'EOF'
用法：sudo tools/kmscon.sh <命令> [tty]

命令：
  status            显示当前状态，不做任何改动
  trial [tty]       在备用 tty（默认 tty3）试运行；图形会话运行时通常起不来
  enable [tty]      正式切换到 KMSCON（默认 tty1），重启后生效
  disable [tty]     回滚到内核控制台 agetty（默认 tty1）

说明：
  - 字体和字号在 /etc/kmscon/kmscon.conf 里配置（font-name、font-size）。
  - Arch 的 ly-kmsconvt@.service 硬编码了 --font-engine unifont，
    会忽略上面的 font-name；本脚本用 drop-in 去掉它。
  - enable/disable 只改 systemd 配置，重启（或手动 restart）后生效。
  - kmscon 需要独占 GPU。已有 Wayland/X11 会话在跑时，trial 往往无法
    取得 DRM master，界面会是黑的；第一次切换建议直接 enable 后重启。
EOF
}

die() { echo "$*" >&2; exit 1; }

require_root() {
    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        die "需要 root 权限：sudo $0 $*"
    fi
}

require_tools() {
    local missing=() c
    for c in kmscon ly-dm kmscon-launch-gui; do
        command -v "$c" >/dev/null || missing+=("$c")
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        die "缺少依赖：${missing[*]}（需要 kmscon 与带 KMSCON 支持的 Ly）"
    fi
}

valid_tty() {
    [[ "$1" =~ ^tty[0-9]+$ ]] || die "无效的 tty：$1（示例：tty1）"
}

write_dropin() {
    mkdir -p "$DROPIN_DIR"
    cat > "$DROPIN" <<'EOF'
# GENERATED by tools/kmscon.sh; 说明见 docs/kmscon.md。
# Arch 的 ly-kmsconvt@.service 硬编码 --font-engine unifont，
# 会忽略 /etc/kmscon/kmscon.conf 的 font-name。清空后使用不带该参数的版本，
# 交给 kmscon 走 freetype/pango，从而应用配置里的字体。
[Service]
ExecStart=
ExecStart=/usr/bin/kmscon --term=linux --vt=%I --login -- /usr/bin/ly-dm --use-kmscon-vt
EOF
    systemctl daemon-reload
    echo "已写入 $DROPIN"
}

remove_dropin() {
    if [[ -e "$DROPIN" ]]; then
        rm -f "$DROPIN"
        rmdir "$DROPIN_DIR" 2>/dev/null || true
        systemctl daemon-reload
        echo "已移除 $DROPIN"
    fi
}

kmscon_font() {
    local conf=/etc/kmscon/kmscon.conf
    if [[ ! -r "$conf" ]]; then
        echo "  (无 $conf)"
        return
    fi
    grep -E '^[[:space:]]*(font-name|font-size|term)[[:space:]]*=' "$conf" | sed 's/^/  /' || true
}

cmd_status() {
    echo "== 已启用的 Ly 服务 =="
    local found
    found=$(ls -1 /etc/systemd/system/multi-user.target.wants/ 2>/dev/null | grep -E '^(ly|ly-kmsconvt)@' || true)
    [[ -n "$found" ]] && echo "$found" | sed 's/^/  /' || echo "  (无)"
    echo
    echo "== 字体 drop-in =="
    if [[ -e "$DROPIN" ]]; then echo "  已存在：$DROPIN"; else echo "  不存在"; fi
    echo
    echo "== /etc/kmscon/kmscon.conf =="
    kmscon_font
    echo
    echo "== 依赖 =="
    local c
    for c in kmscon ly-dm kmscon-launch-gui; do
        printf '  %-18s %s\n' "$c" "$(command -v "$c" || echo '缺失')"
    done
}

cmd_trial() {
    require_root "$@"
    require_tools
    local tty="${1:-$TRIAL_TTY}"
    valid_tty "$tty"
    write_dropin
    systemctl restart "ly-kmsconvt@$tty.service"

    # 成功的 kmscon 会拉起登录子进程（ly-dm）；失败时只剩一个 (kmscon) 主进程。
    local pid up='' i
    for i in $(seq 1 15); do
        pid=$(systemctl show -p MainPID --value "ly-kmsconvt@$tty.service" 2>/dev/null || echo 0)
        if [[ -n "$pid" && "$pid" != 0 ]] && pgrep -P "$pid" >/dev/null 2>&1; then
            up=1
            break
        fi
        sleep 0.2
    done

    echo "已在 $tty 启动 KMSCON。按 Ctrl+Alt+F${tty#tty} 查看（若无效可试 sudo chvt ${tty#tty}）。"
    if [[ -z "$up" ]]; then
        cat >&2 <<EOF

警告：kmscon 没有拉起登录进程，界面大概率是黑的。
最常见原因：当前有 Wayland/X11 会话（如 niri）正占用 GPU，kmscon 拿不到 DRM master。
kmscon 要独占显卡，所以不适合在图形会话运行时试跑。

请改用正式切换并重启：
  sudo $0 enable
  sudo reboot
EOF
        return 2
    fi
}

cmd_enable() {
    require_root "$@"
    require_tools
    local tty="${1:-$DEFAULT_TTY}"
    valid_tty "$tty"
    write_dropin
    systemctl disable "ly@$tty.service" 2>/dev/null || true
    systemctl enable "ly-kmsconvt@$tty.service"
    echo "已启用 ly-kmsconvt@$tty.service。"
    echo "重启后生效，或执行：sudo systemctl restart ly-kmsconvt@$tty.service（会结束该 tty 上的会话）"
}

cmd_disable() {
    require_root "$@"
    local tty="${1:-$DEFAULT_TTY}"
    valid_tty "$tty"
    systemctl disable "ly-kmsconvt@$tty.service" 2>/dev/null || true
    systemctl enable "ly@$tty.service"
    remove_dropin
    echo "已回滚到 ly@$tty.service。重启后生效。"
}

main() {
    local cmd="${1:-}"
    shift || true
    case "$cmd" in
        status)  cmd_status "$@" ;;
        trial)   cmd_trial "$@" ;;
        enable)  cmd_enable "$@" ;;
        disable) cmd_disable "$@" ;;
        ''|-h|--help|help) usage ;;
        *) usage >&2; exit 2 ;;
    esac
}

main "$@"
